<a href="https://colab.research.google.com/github/Dhaks13/DL_using_PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.3.1+cu121'

### Introduction to Tensors
  Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix

matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [16]:
matrix.shape

torch.Size([2, 2])

In [18]:
#TENSOR

TENSOR = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])