In [1]:
!nvidia-smi

Sat Jul 20 10:23:51 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   58C    P0             14W /   75W |     414MiB /   4096MiB |     15%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.3.1+cu121'

### Introduction to Tensors
  Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix

matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
#TENSOR

TENSOR = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Using Random Tensors!

In [17]:
#creating a random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4818, 0.6030, 0.7718, 0.2009],
        [0.1203, 0.3002, 0.8894, 0.3395],
        [0.7608, 0.5421, 0.1306, 0.1010]])

In [18]:
random_tensor2 = torch.rand(10,10,10)
random_tensor2

tensor([[[4.3908e-01, 2.9842e-01, 1.9783e-01, 9.2173e-01, 4.7173e-01,
          9.5473e-01, 4.6631e-01, 9.5536e-01, 9.4331e-01, 4.0815e-02],
         [7.1037e-01, 8.1769e-01, 7.0629e-01, 6.8197e-01, 3.1877e-01,
          2.2318e-01, 1.6812e-01, 3.5469e-02, 9.5208e-01, 2.3691e-01],
         [3.6869e-01, 7.3766e-01, 4.5267e-01, 7.0032e-01, 8.5627e-02,
          5.1850e-01, 5.0212e-01, 2.9993e-01, 3.6671e-01, 3.2754e-01],
         [3.7149e-01, 3.2421e-01, 3.5276e-01, 7.7696e-01, 4.9577e-01,
          2.3186e-01, 9.3287e-02, 8.9519e-01, 4.6904e-01, 6.4806e-01],
         [4.8753e-01, 1.2097e-01, 7.1258e-01, 1.2801e-01, 9.7862e-01,
          1.0344e-01, 2.0462e-01, 5.8081e-01, 6.7634e-01, 2.4880e-01],
         [8.4437e-02, 2.4211e-01, 6.5772e-01, 1.8393e-01, 4.3148e-01,
          1.0455e-01, 4.0979e-01, 2.8522e-01, 5.7935e-01, 1.0172e-01],
         [2.3878e-01, 4.5680e-02, 8.4886e-02, 9.5099e-01, 9.5131e-01,
          9.5683e-02, 7.1535e-01, 3.4925e-01, 4.9948e-01, 8.8551e-01],
         [9.6

In [19]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#ZEROs and ONEs Tensor


In [20]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype, random_image_size_tensor.dtype

(torch.float32, torch.float32)

#Creating a range of Tensor

In [23]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Getting info from tensors

In [24]:
some_tensor=torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.6127, 0.5961, 0.3858, 0.8670],
        [0.3072, 0.2170, 0.6230, 0.0776],
        [0.2370, 0.1269, 0.3815, 0.6535]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


# Manipulating Tensors
* Add
* Sub
* Mul
* Div
* Matrix Mul

In [25]:
#creating tensor and do operations
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [26]:
# or can use .add  or .operator()
#ex
tensor.add(10)

tensor([11, 12, 13])

#Matrix Multiplication

In [29]:
#two type of mul
#normal multiplication
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
print(tensor1,"*",tensor2,"=",tensor1*tensor2)


tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [30]:
#Matrix multiply
print("\nMatrix Mul: ",tensor1.matmul(tensor2))


Matrix Mul:  tensor(14)


### FInding
* Min
* max
* mean
* sum

In [31]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [34]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [35]:
#raise error due to datatype problem
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [36]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [37]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

# Finding Positional of min and max

In [39]:
print("Min pos: ",x.argmin())
print("Max pos: ",x.argmax())

Min pos:  tensor(0)
Max pos:  tensor(9)


# Reshaping, sacking, squeezing and unsqueezing

In [40]:
x = torch.arange(1.,13.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [41]:
x_reshaped = x.reshape(6,2)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [42]:
#changing the view
z = x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [43]:
# changing z changes x
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [44]:
#Stacking
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [45]:
#squeeze
print (x_reshaped)
x_reshaped = x_reshaped.reshape(1,12)
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])


tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [46]:
#unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [47]:
#permute
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [48]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

# Indexing (Selecting data from tensor)

In [49]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
x[0][0]

tensor([1, 2, 3])

In [52]:
x[0][0][0]

tensor(1)

In [53]:
x[:,2]

tensor([[7, 8, 9]])

In [54]:
x[:,:,1]

tensor([[2, 5, 8]])

In [55]:
x[:,1,1]

tensor([5])

## PyTorch tensor and NumPy

In [56]:
#NumPy arr to Tensors
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Reproducbility

In [57]:
#creating random tensor
tensora = torch.rand(3,4)
tensorb = torch.rand(3,4)
print(tensora)
print(tensorb)
print(tensora==tensorb)

tensor([[0.5199, 0.6624, 0.1158, 0.6271],
        [0.2643, 0.1837, 0.7430, 0.5605],
        [0.6783, 0.7117, 0.2313, 0.7904]])
tensor([[0.0457, 0.0274, 0.2871, 0.9550],
        [0.3203, 0.1607, 0.1208, 0.5600],
        [0.9864, 0.5996, 0.7245, 0.8183]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [58]:
#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [59]:
torch.manual_seed(RANDOM_SEED)

# Running code on GPUs
Makes the computation faster

In [60]:
torch.cuda.is_available()

True