In [1]:
!nvidia-smi

Sat Jul 20 10:39:19 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   54C    P0             14W /   75W |     462MiB /   4096MiB |     15%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.3.1+cu121'

### Introduction to Tensors
  Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix

matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
#TENSOR

TENSOR = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Using Random Tensors!

In [17]:
#creating a random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4831, 0.0312, 0.1407, 0.2567],
        [0.1605, 0.4163, 0.1444, 0.0830],
        [0.5687, 0.3211, 0.1324, 0.4149]])

In [18]:
random_tensor2 = torch.rand(10,10,10)
random_tensor2

tensor([[[6.0831e-01, 8.9019e-01, 8.7428e-01, 1.4576e-01, 8.3215e-01,
          2.7381e-02, 8.8369e-02, 4.7936e-01, 6.0519e-01, 8.0731e-01],
         [9.7700e-01, 4.7728e-01, 5.9242e-01, 3.1199e-01, 7.6182e-01,
          9.3784e-01, 2.8844e-01, 1.7467e-01, 7.0292e-01, 6.6832e-01],
         [5.4849e-02, 2.4774e-01, 7.3958e-01, 5.9616e-01, 9.6059e-02,
          1.4831e-01, 4.3626e-01, 5.4141e-01, 7.3638e-01, 8.6096e-01],
         [8.4594e-01, 6.9318e-01, 8.8350e-01, 7.9155e-01, 1.9249e-01,
          9.6479e-01, 6.4358e-01, 9.8407e-01, 9.6810e-01, 4.0409e-01],
         [2.9036e-01, 6.8624e-01, 9.7299e-01, 8.8829e-01, 4.1381e-01,
          5.0009e-02, 5.4299e-01, 3.7395e-01, 5.2122e-01, 8.0832e-01],
         [3.9899e-01, 3.9466e-01, 9.5727e-01, 7.8501e-01, 1.8192e-01,
          8.8546e-01, 3.4983e-01, 1.4025e-01, 7.2327e-02, 9.4943e-02],
         [6.4453e-01, 9.6644e-01, 3.5942e-01, 1.8369e-02, 3.8216e-01,
          8.8153e-01, 8.9882e-01, 8.6523e-01, 9.6075e-01, 3.5487e-02],
         [4.3

In [19]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#ZEROs and ONEs Tensor


In [20]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype, random_image_size_tensor.dtype

(torch.float32, torch.float32)

#Creating a range of Tensor

In [23]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Getting info from tensors

In [24]:
some_tensor=torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.9039, 0.1383, 0.1678, 0.3890],
        [0.2353, 0.4011, 0.8142, 0.9841],
        [0.0243, 0.4921, 0.2416, 0.5581]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


# Manipulating Tensors
* Add
* Sub
* Mul
* Div
* Matrix Mul

In [25]:
#creating tensor and do operations
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [26]:
# or can use .add  or .operator()
#ex
tensor.add(10)

tensor([11, 12, 13])

#Matrix Multiplication

In [27]:
#two type of mul
#normal multiplication
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
print(tensor1,"*",tensor2,"=",tensor1*tensor2)


tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [28]:
#Matrix multiply
print("\nMatrix Mul: ",tensor1.matmul(tensor2))


Matrix Mul:  tensor(14)


### FInding
* Min
* max
* mean
* sum

In [29]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [31]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [32]:
#raise error due to datatype problem
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [33]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [34]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

# Finding Positional of min and max

In [35]:
print("Min pos: ",x.argmin())
print("Max pos: ",x.argmax())

Min pos:  tensor(0)
Max pos:  tensor(9)


# Reshaping, sacking, squeezing and unsqueezing

In [36]:
x = torch.arange(1.,13.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [37]:
x_reshaped = x.reshape(6,2)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [38]:
#changing the view
z = x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [39]:
# changing z changes x
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [40]:
#Stacking
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [41]:
#squeeze
print (x_reshaped)
x_reshaped = x_reshaped.reshape(1,12)
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])


tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [42]:
#unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [43]:
#permute
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [44]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

# Indexing (Selecting data from tensor)

In [45]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [46]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [47]:
x[0][0]

tensor([1, 2, 3])

In [48]:
x[0][0][0]

tensor(1)

In [49]:
x[:,2]

tensor([[7, 8, 9]])

In [50]:
x[:,:,1]

tensor([[2, 5, 8]])

In [51]:
x[:,1,1]

tensor([5])

## PyTorch tensor and NumPy

In [52]:
#NumPy arr to Tensors
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Reproducbility

In [53]:
#creating random tensor
tensora = torch.rand(3,4)
tensorb = torch.rand(3,4)
print(tensora)
print(tensorb)
print(tensora==tensorb)

tensor([[0.9708, 0.3574, 0.9489, 0.2684],
        [0.0888, 0.2220, 0.5680, 0.8620],
        [0.9569, 0.7580, 0.2251, 0.2814]])
tensor([[0.1861, 0.9569, 0.9583, 0.4167],
        [0.0020, 0.3131, 0.6459, 0.4972],
        [0.4368, 0.7835, 0.1060, 0.5558]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [54]:
#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [55]:
torch.manual_seed(RANDOM_SEED)

# Running code on GPUs
Makes the computation faster

In [56]:
torch.cuda.is_available()

True