In [ ]:
!nvidia-smi

Sat Jul 20 04:51:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.3.1+cu121'

### Introduction to Tensors
  Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix

matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Using Random Tensors!

In [ ]:
#creating a random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9369, 0.6295, 0.9428, 0.4347],
        [0.3415, 0.3622, 0.1333, 0.4121],
        [0.7865, 0.3549, 0.6294, 0.4965]])

In [ ]:
random_tensor2 = torch.rand(10,10,10)
random_tensor2

tensor([[[6.0228e-01, 9.5259e-02, 5.2197e-01, 4.8435e-01, 5.7351e-01,
          5.1907e-01, 8.4273e-01, 1.2708e-01, 6.7976e-01, 7.2893e-01],
         [3.0525e-01, 9.2524e-01, 4.5454e-01, 8.8424e-01, 4.8413e-01,
          9.1346e-01, 5.7126e-01, 4.6493e-01, 5.1040e-01, 3.2927e-01],
         [1.7458e-01, 8.8896e-01, 5.2679e-01, 1.5891e-01, 2.0498e-01,
          7.6585e-01, 5.5677e-02, 6.1787e-01, 6.8090e-02, 4.4254e-01],
         [4.8462e-01, 4.5516e-01, 8.2666e-02, 5.3205e-01, 6.6954e-03,
          2.7748e-01, 7.9553e-01, 1.3821e-01, 2.6808e-01, 6.7516e-01],
         [5.5377e-01, 5.5698e-01, 9.0020e-02, 6.5142e-01, 7.1265e-01,
          6.8791e-01, 4.7631e-01, 4.2683e-01, 1.9446e-01, 2.7461e-01],
         [6.7469e-02, 7.6981e-01, 1.0392e-01, 3.6010e-01, 3.8184e-01,
          9.3450e-01, 4.7134e-01, 5.4278e-02, 8.5927e-01, 3.9925e-01],
         [8.9334e-01, 8.4333e-01, 8.2614e-01, 4.6109e-01, 7.1462e-01,
          8.5429e-01, 2.8066e-01, 6.9030e-01, 7.5554e-01, 4.4418e-01],
         [5.9

In [ ]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#ZEROs and ONEs Tensor


In [ ]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype, random_image_size_tensor.dtype

(torch.float32, torch.float32)

#Creating a range of Tensor

In [ ]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Getting info from tensors

In [ ]:
some_tensor=torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.1271, 0.5440, 0.4965, 0.8567],
        [0.7887, 0.5175, 0.4151, 0.0250],
        [0.1283, 0.0816, 0.6647, 0.4918]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


# Manipulating Tensors
* Add
* Sub
* Mul
* Div
* Matrix Mul

In [ ]:
#creating tensor and do operations
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
# or can use .add  or .operator()
#ex
tensor.add(10)

tensor([11, 12, 13])

#Matrix Multiplication

In [ ]:
#two type of mul
%%time
#normal multiplication
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
print(tensor1,"*",tensor2,"=",tensor1*tensor2)


tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])
CPU times: user 886 µs, sys: 0 ns, total: 886 µs
Wall time: 1.2 ms


In [ ]:
%%time
#Matrix multiply
print("\nMatrix Mul: ",tensor1.matmul(tensor2))


Matrix Mul:  tensor(14)
CPU times: user 1.89 ms, sys: 0 ns, total: 1.89 ms
Wall time: 6.95 ms


### FInding
* Min
* max
* mean
* sum

In [ ]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
#raise error due to datatype problem
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

# Finding Positional of min and max

In [ ]:
print("Min pos: ",x.argmin())
print("Max pos: ",x.argmax())

Min pos:  tensor(0)
Max pos:  tensor(9)


# Reshaping, sacking, squeezing and unsqueezing

In [ ]:
x = torch.arange(1.,13.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
x_reshaped = x.reshape(6,2)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [ ]:
#changing the view
z = x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [ ]:
# changing z changes x
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [ ]:
#Stacking
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
#squeeze
print (x_reshaped)
x_reshaped = x_reshaped.reshape(1,12)
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])


tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
#unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
#permute
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [ ]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

# Indexing (Selecting data from tensor)

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[:,2]

tensor([[7, 8, 9]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

## PyTorch tensor and NumPy

In [ ]:
#NumPy arr to Tensors
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Reproducbility

In [ ]:
#creating random tensor
tensora = torch.rand(3,4)
tensorb = torch.rand(3,4)
print(tensora)
print(tensorb)
print(tensora==tensorb)

tensor([[0.5527, 0.0093, 0.4139, 0.1552],
        [0.6930, 0.6984, 0.9492, 0.5784],
        [0.9673, 0.7580, 0.4352, 0.5020]])
tensor([[0.2210, 0.2898, 0.1604, 0.7409],
        [0.4807, 0.9687, 0.3524, 0.9186],
        [0.1001, 0.0655, 0.4527, 0.4771]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
torch.manual_seed(RANDOM_SEED)

# Running code on GPUs
Makes the computation faster

In [ ]:
torch.cuda.is_available()

True