<a href="https://colab.research.google.com/github/Dhaks13/DL_using_PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [79]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.3.1+cu121'

### Introduction to Tensors
  Creating Tensors

In [80]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [81]:
scalar.ndim

0

In [82]:
scalar.item()

7

In [83]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [84]:
vector.ndim

1

In [85]:
vector.shape

torch.Size([2])

In [86]:
#Matrix

matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [87]:
matrix.ndim

2

In [88]:
matrix[1]

tensor([ 9, 10])

In [89]:
matrix.shape

torch.Size([2, 2])

In [90]:
#TENSOR

TENSOR = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [91]:
TENSOR.ndim

3

In [92]:
TENSOR.shape

torch.Size([1, 3, 3])

In [93]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Using Random Tensors!

In [94]:
#creating a random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7641, 0.4147, 0.5975, 0.8735],
        [0.9683, 0.6024, 0.4276, 0.7259],
        [0.0721, 0.2907, 0.2563, 0.6301]])

In [95]:
random_tensor2 = torch.rand(10,10,10)
random_tensor2

tensor([[[0.4986, 0.3788, 0.7808, 0.0548, 0.4513, 0.4090, 0.8661, 0.0310,
          0.0399, 0.4725],
         [0.7306, 0.7179, 0.9198, 0.5486, 0.2974, 0.1017, 0.7447, 0.2678,
          0.5583, 0.2015],
         [0.4837, 0.8548, 0.7303, 0.0454, 0.5870, 0.5824, 0.9964, 0.0976,
          0.4684, 0.0914],
         [0.2898, 0.7084, 0.9063, 0.4698, 0.4898, 0.8904, 0.0679, 0.7022,
          0.1869, 0.0592],
         [0.7042, 0.4078, 0.5431, 0.5665, 0.7583, 0.1186, 0.0487, 0.4755,
          0.6529, 0.8759],
         [0.8768, 0.9268, 0.3697, 0.0973, 0.4963, 0.6271, 0.4893, 0.7706,
          0.6779, 0.4044],
         [0.4726, 0.1311, 0.1237, 0.9102, 0.8520, 0.5159, 0.2046, 0.6405,
          0.8835, 0.9474],
         [0.6309, 0.1492, 0.7221, 0.7771, 0.1432, 0.7880, 0.6495, 0.6830,
          0.1320, 0.7550],
         [0.9944, 0.3412, 0.3433, 0.7485, 0.4810, 0.0944, 0.6574, 0.9476,
          0.8502, 0.1143],
         [0.4880, 0.7855, 0.3515, 0.8420, 0.2589, 0.9793, 0.3683, 0.2728,
          0.9600,

In [96]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#ZEROs and ONEs Tensor


In [97]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [98]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
ones.dtype, random_image_size_tensor.dtype

(torch.float32, torch.float32)

#Creating a range of Tensor

In [100]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Getting info from tensors

In [101]:
some_tensor=torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.3524, 0.3722, 0.8313, 0.4344],
        [0.2477, 0.7908, 0.3004, 0.6946],
        [0.7984, 0.7819, 0.9456, 0.1602]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


# Manipulating Tensors
* Add
* Sub
* Mul
* Div
* Matrix Mul

In [102]:
#creating tensor and do operations
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [103]:
# or can use .add  or .operator()
#ex
tensor.add(10)

tensor([11, 12, 13])

#Matrix Multiplication

In [104]:
#two type of mul
%%time
#normal multiplication
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
print(tensor1,"*",tensor2,"=",tensor1*tensor2)


tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])
CPU times: user 5.44 ms, sys: 0 ns, total: 5.44 ms
Wall time: 9.39 ms


In [105]:
%%time
#Matrix multiply
print("\nMatrix Mul: ",tensor1.matmul(tensor2))


Matrix Mul:  tensor(14)
CPU times: user 2.19 ms, sys: 0 ns, total: 2.19 ms
Wall time: 2.2 ms


### FInding
* Min
* max
* mean
* sum

In [106]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [108]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [109]:
#raise error due to datatype problem
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [110]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [111]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

# Finding Positional of min and max

In [112]:
print("Min pos: ",x.argmin())
print("Max pos: ",x.argmax())

Min pos:  tensor(0)
Max pos:  tensor(9)


# Reshaping, sacking, squeezing and unsqueezing

In [113]:
x = torch.arange(1.,13.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [114]:
x_reshaped = x.reshape(6,2)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [115]:
#changing the view
z = x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [116]:
# changing z changes x
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [117]:
#Stacking
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [118]:
#squeeze
print (x_reshaped)
x_reshaped = x_reshaped.reshape(1,12)
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])


tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [119]:
#unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [120]:
#permute
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [121]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])