<a href="https://colab.research.google.com/github/Dhaks13/DL_using_PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.3.1+cu121'

### Introduction to Tensors
  Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix

matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
#TENSOR

TENSOR = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Using Random Tensors!

In [17]:
#creating a random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3872, 0.9463, 0.5512, 0.1808],
        [0.4608, 0.7764, 0.5950, 0.7025],
        [0.5362, 0.2094, 0.9354, 0.1585]])

In [18]:
random_tensor2 = torch.rand(10,10,10)
random_tensor2

tensor([[[0.4318, 0.6371, 0.2909, 0.3177, 0.6333, 0.2147, 0.2962, 0.7300,
          0.8111, 0.2951],
         [0.8054, 0.6410, 0.1749, 0.6164, 0.0393, 0.1931, 0.5786, 0.0967,
          0.8114, 0.0067],
         [0.0189, 0.5144, 0.0667, 0.7439, 0.9258, 0.9467, 0.3097, 0.8256,
          0.5042, 0.4494],
         [0.7470, 0.1589, 0.3211, 0.1540, 0.5066, 0.6129, 0.7832, 0.7070,
          0.4148, 0.6799],
         [0.6297, 0.9158, 0.0130, 0.2845, 0.9010, 0.5624, 0.6728, 0.5619,
          0.8326, 0.3683],
         [0.3632, 0.8408, 0.4439, 0.3834, 0.6190, 0.4156, 0.6083, 0.5189,
          0.1107, 0.9044],
         [0.1365, 0.8713, 0.6325, 0.1353, 0.6706, 0.9978, 0.1076, 0.3803,
          0.1464, 0.8669],
         [0.4910, 0.4690, 0.7474, 0.7745, 0.7912, 0.7933, 0.3794, 0.7013,
          0.4913, 0.7716],
         [0.5476, 0.4424, 0.3217, 0.0968, 0.7304, 0.5894, 0.7214, 0.4098,
          0.8928, 0.6211],
         [0.9684, 0.7719, 0.2117, 0.6879, 0.9470, 0.5514, 0.8473, 0.5234,
          0.1322,

In [19]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#ZEROs and ONEs Tensor


In [20]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype, random_image_size_tensor.dtype

(torch.float32, torch.float32)

#Creating a range of Tensor

In [23]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Getting info from tensors

In [24]:
some_tensor=torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.7582, 0.5189, 0.3942, 0.4708],
        [0.6988, 0.9461, 0.8052, 0.9589],
        [0.0072, 0.1414, 0.1570, 0.5392]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


# Manipulating Tensors
* Add
* Sub
* Mul
* Div
* Matrix Mul

In [25]:
#creating tensor and do operations
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [26]:
# or can use .add  or .operator()
#ex
tensor.add(10)

tensor([11, 12, 13])

#Matrix Multiplication

In [27]:
#two type of mul
%%time
#normal multiplication
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
print(tensor1,"*",tensor2,"=",tensor1*tensor2)


tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])
CPU times: user 4.04 ms, sys: 1.18 ms, total: 5.21 ms
Wall time: 13.1 ms


In [28]:
%%time
#Matrix multiply
print("\nMatrix Mul: ",tensor1.matmul(tensor2))


Matrix Mul:  tensor(14)
CPU times: user 4.87 ms, sys: 169 µs, total: 5.04 ms
Wall time: 20.7 ms


### FInding
* Min
* max
* mean
* sum

In [29]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [31]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [33]:
#raise error due to datatype problem
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [34]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x),x.sum()

# Finding Positional of min and max

In [35]:
print("Min pos: ",x.argmin())
print("Max pos: ",x.argmax())

Min pos:  tensor(0)
Max pos:  tensor(9)


# Reshaping, sacking, squeezing and unsqueezing

In [36]:
x = torch.arange(1.,13.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [37]:
x_reshaped = x.reshape(6,2)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [38]:
#changing the view
z = x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [39]:
# changing z changes x
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [40]:
#Stacking
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [41]:
#squeeze
print (x_reshaped)
x_reshaped = x_reshaped.reshape(1,12)
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])


tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [42]:
#unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [43]:
#permute
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [44]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

# Indexing (Selecting data from tensor)

In [46]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [47]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x[0][0]

tensor([1, 2, 3])

In [49]:
x[0][0][0]

tensor(1)

In [51]:
x[:,2]

tensor([[7, 8, 9]])

In [52]:
x[:,:,1]

tensor([[2, 5, 8]])

In [57]:
x[:,1,1]

tensor([5])

## PyTorch tensor and NumPy

In [58]:
#NumPy arr to Tensors
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Reproducbility

In [61]:
#creating random tensor
tensora = torch.rand(3,4)
tensorb = torch.rand(3,4)
print(tensora)
print(tensorb)
print(tensora==tensorb)

tensor([[0.5178, 0.8702, 0.3783, 0.2519],
        [0.6478, 0.4301, 0.3315, 0.0259],
        [0.8952, 0.5951, 0.6630, 0.5176]])
tensor([[0.2705, 0.3757, 0.8396, 0.6060],
        [0.4612, 0.1924, 0.8504, 0.0856],
        [0.5542, 0.8061, 0.2655, 0.3330]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [65]:
#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [67]:
torch.manual_seed(RANDOM_SEED)

# Running code on GPUs
Makes the computation faster